/**
 * Zerops API client — used by the Shipyard to create and deploy user apps on Zerops.
 * Zerops REST API: https://app.zerops.io/api/rest/v1
 * Auth: Bearer token from ZEROPS_API_TOKEN env var
 */

const ZEROPS_API = 'https://app.zerops.io/api/rest/v1'

function getToken(): string {
    const token = process.env.ZEROPS_API_TOKEN
    if (!token) throw new Error('ZEROPS_API_TOKEN is not set')
    return token
}

function headers() {
    return {
        Authorization: `Bearer ${getToken()}`,
        'Content-Type': 'application/json',
    }
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await fetch(`${ZEROPS_API}${path}`, {
        method,
        headers: headers(),
        body: body ? JSON.stringify(body) : undefined,
    })
    if (!res.ok) {
        const text = await res.text()
        throw new Error(`Zerops API ${method} ${path} → ${res.status}: ${text}`)
    }
    return res.json() as Promise<T>
}

// ─── Types ──────────────────────────────────────────────────────────────────

interface ZeropsProject {
    id: string
    name: string
    status: string
}

interface ZeropsService {
    id: string
    name: string
    hostname: string
    status: string
    subdomain?: string
}

interface ZeropsDeployment {
    id: string
    status: 'PENDING' | 'DEPLOYING' | 'ACTIVE' | 'FAILED' | 'STOPPED'
    url?: string
}

interface ProjectResponse {
    id: string
    project: ZeropsProject
}

// ─── Client ─────────────────────────────────────────────────────────────────

export const zeropsClient = {
    /**
     * Create a new Zerops project for a generated user app.
     * Returns the project ID used for subsequent operations.
     */
    createProject: async (params: {
        name: string
        description?: string
    }): Promise<{ projectId: string }> => {
        console.log(`[Zerops] Creating project: ${params.name}`)
        const data = await request<{ id: string }>('POST', '/project', {
            name: params.name,
            description: params.description ?? 'Generated by ForgeOS Node Studio',
            tags: ['forgeos', 'generated'],
        })
        console.log(`[Zerops] ✅ Project created: ${data.id}`)
        return { projectId: data.id }
    },

    /**
     * Add a Node.js service to a project (for the generated app's API).
     */
    addNodeService: async (params: {
        projectId: string
        hostname: string
        githubRepo: string  // full name e.g. "org/repo"
        branch?: string
    }): Promise<{ serviceId: string }> => {
        console.log(`[Zerops] Adding Node.js service to project ${params.projectId}`)
        const data = await request<{ id: string }>('POST', `/project/${params.projectId}/service-stack`, {
            hostname: params.hostname,
            type: 'NODEJS',
            mode: 'NON_HA',
            verticalAutoscaling: {
                minVCpu: 0.5,
                maxVCpu: 4,
                minRam: 0.25,
                maxRam: 4,
            },
            githubIntegration: {
                repository: params.githubRepo,
                branch: params.branch ?? 'main',
                deployOnPush: true,
            },
        })
        return { serviceId: data.id }
    },

    /**
     * Trigger a deploy pipeline for a service.
     */
    triggerDeploy: async (serviceId: string): Promise<{ pipelineId: string }> => {
        console.log(`[Zerops] Triggering deploy for service ${serviceId}`)
        const data = await request<{ id: string }>('POST', `/service-stack/${serviceId}/deploy-pipeline`, {})
        return { pipelineId: data.id }
    },

    /**
     * Get the public URL for a service (if subdomain is enabled).
     */
    getServiceUrl: async (serviceId: string): Promise<string | null> => {
        const data = await request<ZeropsService>('GET', `/service-stack/${serviceId}`)
        if (data.subdomain) {
            return `https://${data.subdomain}.zerops.app`
        }
        return null
    },

    /**
     * Poll until a service is ACTIVE or FAILED.
     * Returns the live URL, or null on timeout.
     */
    waitForActive: async (
        serviceId: string,
        maxPolls = 20,
        intervalMs = 15_000,
    ): Promise<string | null> => {
        for (let i = 0; i < maxPolls; i++) {
            await new Promise(r => setTimeout(r, intervalMs))
            try {
                const data = await request<ZeropsService>('GET', `/service-stack/${serviceId}`)
                console.log(`[Zerops] Poll ${i + 1}/${maxPolls}: status=${data.status}`)

                if (data.status === 'ACTIVE_HEALTHY' || data.status === 'ACTIVE') {
                    const url = data.subdomain ? `https://${data.subdomain}.zerops.app` : null
                    console.log(`[Zerops] ✅ Service active: ${url}`)
                    return url
                }
                if (data.status === 'FAILED' || data.status === 'STOPPED') {
                    throw new Error(`Zerops service failed with status: ${data.status}`)
                }
            } catch (err) {
                // Re-throw fatal errors, continue on transient fetch failures
                if ((err as Error).message.includes('status:')) throw err
                console.warn(`[Zerops] Poll error (non-fatal):`, err)
            }
        }
        throw new Error('Zerops deployment timed out after max polls')
    },

    /**
     * Enable a public subdomain for a service (so it gets a .zerops.app URL).
     */
    enableSubdomain: async (serviceId: string): Promise<void> => {
        console.log(`[Zerops] Enabling subdomain for service ${serviceId}`)
        await request('PUT', `/service-stack/${serviceId}/subdomain`, { enabled: true })
    },
}
